/**
 * Playwright Code Templates — common patterns for automated test generation.
 *
 * These templates are used as fallbacks and structure guides when the AI
 * generates Playwright test code.
 */

// ---------------------------------------------------------------------------
// Config Template
// ---------------------------------------------------------------------------

export const PLAYWRIGHT_CONFIG_TEMPLATE = `import { defineConfig, devices } from '@playwright/test';

/**
 * Playwright configuration — auto-generated by AI Test Case Generator.
 * See https://playwright.dev/docs/test-configuration
 */
export default defineConfig({
  testDir: './tests/e2e',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',

  use: {
    // TODO: Update baseURL to your application's URL
    baseURL: process.env.BASE_URL || 'http://localhost:3000',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
  },

  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],

  // TODO: Configure your dev server
  // webServer: {
  //   command: 'npm run dev',
  //   url: 'http://localhost:3000',
  //   reuseExistingServer: !process.env.CI,
  // },
});
`;

// ---------------------------------------------------------------------------
// Test File Templates
// ---------------------------------------------------------------------------

export function generateTestFileHeader(featureArea: string): string {
  return `import { test, expect } from '@playwright/test';

/**
 * ${featureArea} — Automated E2E Tests
 *
 * Auto-generated by AI Test Case Generator.
 * Review each test and adjust selectors, URLs, and test data as needed.
 */

`;
}

export function generateTestSkeleton(
  testCaseId: string,
  title: string,
  description: string,
  steps: Array<{ stepNumber: number; action: string; expectedResult: string; testData?: string }>,
  preconditions: string[]
): string {
  const preconditionComments = preconditions.length > 0
    ? preconditions.map((p) => `  // Precondition: ${p}`).join('\n') + '\n'
    : '';

  const stepCode = steps
    .map((step) => {
      return [
        `    // Step ${step.stepNumber}: ${step.action}`,
        `    // Expected: ${step.expectedResult}`,
        step.testData ? `    // Test Data: ${step.testData}` : null,
        `    // TODO: Implement this step`,
        ``,
      ]
        .filter(Boolean)
        .join('\n');
    })
    .join('\n');

  return `test('${title}', async ({ page }) => {
  // Test Case: ${testCaseId}
  // ${description}
${preconditionComments}
${stepCode}
});
`;
}

// ---------------------------------------------------------------------------
// API Test Template
// ---------------------------------------------------------------------------

export function generateAPITestSkeleton(
  testCaseId: string,
  title: string,
  description: string,
  steps: Array<{ stepNumber: number; action: string; expectedResult: string; testData?: string }>
): string {
  const stepCode = steps
    .map((step) => {
      return [
        `    // Step ${step.stepNumber}: ${step.action}`,
        `    // Expected: ${step.expectedResult}`,
        step.testData ? `    // Test Data: ${step.testData}` : null,
        `    // TODO: Implement API call and assertion`,
        ``,
      ]
        .filter(Boolean)
        .join('\n');
    })
    .join('\n');

  return `test('${title}', async ({ request }) => {
  // Test Case: ${testCaseId}
  // ${description}

${stepCode}
});
`;
}
