/**
 * Test Case Formatter — converts TestCase objects to JSON and Markdown.
 *
 * The Markdown output is designed to be human-readable and great for
 * reviewing in pull requests.
 */

import { TestCase } from './types';

// ---------------------------------------------------------------------------
// Single Test Case Formatting
// ---------------------------------------------------------------------------

/**
 * Format a single test case as Markdown.
 */
export function formatTestCaseMarkdown(tc: TestCase): string {
  const priorityEmoji = getPriorityEmoji(tc.priority);
  const typeLabel = tc.type.replace(/_/g, ' ');
  const statusLabel = getStatusLabel(tc.automationStatus);

  let md = `### ${tc.id}: ${tc.title}\n\n`;
  md += `**Priority**: ${priorityEmoji} ${capitalize(tc.priority)} | `;
  md += `**Type**: ${capitalize(typeLabel)} | `;
  md += `**Automation**: ${statusLabel}\n\n`;

  if (tc.description) {
    md += `${tc.description}\n\n`;
  }

  // Preconditions
  if (tc.preconditions.length > 0) {
    md += `#### Preconditions\n`;
    for (const pre of tc.preconditions) {
      md += `- ${pre}\n`;
    }
    md += `\n`;
  }

  // Steps table
  md += `#### Steps\n\n`;
  md += `| # | Action | Expected Result | Test Data |\n`;
  md += `|---|--------|-----------------|----------|\n`;
  for (const step of tc.steps) {
    const data = step.testData || '—';
    md += `| ${step.stepNumber} | ${escapeTable(step.action)} | ${escapeTable(step.expectedResult)} | ${escapeTable(data)} |\n`;
  }
  md += `\n`;

  // Expected Result
  md += `#### Expected Result\n\n`;
  md += `${tc.expectedResult}\n\n`;

  // Related Files
  if (tc.sourceFiles.length > 0) {
    md += `#### Related Files\n`;
    for (const file of tc.sourceFiles) {
      md += `- \`${file}\`\n`;
    }
    md += `\n`;
  }

  // Tags
  if (tc.tags.length > 0) {
    md += `**Tags**: ${tc.tags.map((t) => `\`${t}\``).join(' ')}\n\n`;
  }

  md += `---\n\n`;

  return md;
}

// ---------------------------------------------------------------------------
// Suite Formatting
// ---------------------------------------------------------------------------

/**
 * Format a suite of test cases for a feature area as a single Markdown file.
 */
export function formatTestSuiteMarkdown(featureArea: string, testCases: TestCase[]): string {
  let md = `# ${featureArea} — Test Cases\n\n`;
  md += `> Auto-generated by AI Test Case Generator\n\n`;

  // Summary
  const priorityCounts = {
    critical: testCases.filter((t) => t.priority === 'critical').length,
    high: testCases.filter((t) => t.priority === 'high').length,
    medium: testCases.filter((t) => t.priority === 'medium').length,
    low: testCases.filter((t) => t.priority === 'low').length,
  };

  md += `## Summary\n\n`;
  md += `| Priority | Count |\n`;
  md += `|----------|-------|\n`;
  md += `| 🔴 Critical | ${priorityCounts.critical} |\n`;
  md += `| 🟠 High | ${priorityCounts.high} |\n`;
  md += `| 🟡 Medium | ${priorityCounts.medium} |\n`;
  md += `| 🟢 Low | ${priorityCounts.low} |\n`;
  md += `| **Total** | **${testCases.length}** |\n\n`;

  // Table of Contents
  md += `## Test Cases\n\n`;
  md += `| ID | Title | Priority | Type |\n`;
  md += `|----|-------|----------|------|\n`;
  for (const tc of testCases) {
    md += `| ${tc.id} | ${escapeTable(tc.title)} | ${getPriorityEmoji(tc.priority)} ${capitalize(tc.priority)} | ${capitalize(tc.type)} |\n`;
  }
  md += `\n---\n\n`;

  // Full test cases
  for (const tc of testCases) {
    md += formatTestCaseMarkdown(tc);
  }

  md += `\n*Last updated: ${new Date().toISOString()}*\n`;

  return md;
}

// ---------------------------------------------------------------------------
// JSON Formatting
// ---------------------------------------------------------------------------

/**
 * Format test cases as a JSON string for the test-cases.json file.
 */
export function formatTestCasesJSON(testCases: TestCase[]): string {
  return JSON.stringify(
    {
      version: '1.0.0',
      generatedAt: new Date().toISOString(),
      totalCount: testCases.length,
      testCases,
    },
    null,
    2
  );
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function getPriorityEmoji(priority: string): string {
  switch (priority) {
    case 'critical': return '🔴';
    case 'high': return '🟠';
    case 'medium': return '🟡';
    case 'low': return '🟢';
    default: return '⚪';
  }
}

function getStatusLabel(status: string): string {
  switch (status) {
    case 'pending': return '⏳ Pending';
    case 'generated': return '🤖 Generated';
    case 'verified': return '✅ Verified';
    default: return status;
  }
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function escapeTable(text: string): string {
  return text.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}
